# Generated by Django 5.2.8 on 2026-03-19 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluesky', '0001_initial'),
        ('content', '0006_profilepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueskyPostMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_uri', models.CharField(max_length=512, unique=True)),
                ('source_cid', models.CharField(max_length=128)),
                ('source_did', models.CharField(max_length=255)),
                ('source_rkey', models.CharField(max_length=255)),
                ('source_indexed_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('micro_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluesky_post_maps', to='content.micropostpage')),
                ('source_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_maps', to='bluesky.blueskysourcesettings')),
            ],
            options={
                'ordering': ['-source_indexed_at', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('source_uri',), name='unique_bluesky_post_map_source_uri')],
            },
        ),
    ]
