# Generated by Django 5.2.8 on 2026-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bluesky", "0002_blueskypostmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueskypostmap",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
