# Generated by Django 5.2.8 on 2026-03-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bluesky", "0003_blueskypostmap_removed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueskySyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("removed_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "source_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="bluesky.blueskysourcesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_settings", "-completed_at", "-created_at"],
                        name="bluesky_sr_src_comp_idx",
                    )
                ],
            },
        ),
    ]
