# Generated by Django 5.2.8 on 2026-03-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluesky', '0004_blueskysyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueskysourcesettings',
            name='sync_lock_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueskysourcesettings',
            name='sync_lock_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
