# Generated by Django 5.2.5 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GadgetSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("repo_full_name", models.CharField(max_length=255, unique=True)),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("published", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=1000)),
                ("last_synced_sha", models.CharField(blank=True, max_length=40)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("success", "Success"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True)),
                ("commit_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["display_order", "slug"],
            },
        ),
    ]
