# Generated by Django 5.2.8 on 2025-12-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_blogindexpage_social_image_blogpage_social_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
