# Generated by Django 5.2.8 on 2026-03-13 17:15

import django.db.models.deletion
import modelcluster.contrib.taggit
from django.db import migrations, models


def create_default_profile_page(apps, schema_editor):
    from wagtail.models import Page, Site

    ContentType = apps.get_model("contenttypes", "ContentType")
    ProfilePage = apps.get_model("content", "ProfilePage")

    if Page.objects.filter(
        slug="profile", content_type__app_label="content", content_type__model="profilepage"
    ).exists():
        return

    site = Site.objects.order_by("id").first()
    if not site:
        return

    parent_page = site.root_page
    profile_page_content_type, _ = ContentType.objects.get_or_create(
        app_label="content",
        model="profilepage",
    )

    profile_page = ProfilePage(
        title="Profile",
        slug="profile",
        content_type_id=profile_page_content_type.id,
        locale_id=parent_page.locale_id,
    )
    parent_page.add_child(instance=profile_page)
    Page.objects.get(pk=profile_page.pk).specific.save_revision().publish()


def remove_default_profile_page(apps, schema_editor):
    from wagtail.models import Page

    for page in Page.objects.filter(
        slug="profile", content_type__app_label="content", content_type__model="profilepage"
    ):
        page.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_contentpagetag_blogindexpage_tags_blogpage_tags_and_more"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
        ("wagtailsearch", "0009_remove_ngram_autocomplete"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "social_image",
                    models.ImageField(
                        blank=True, help_text="The image to use in social sharing metadata.", null=True, upload_to=""
                    ),
                ),
                ("intro", models.TextField(default="I'm Taylor Schaack - an operator turned software builder.")),
                (
                    "background",
                    models.TextField(
                        default="My background is unusual by design: I've led operations, sales, and large cross-functional initiatives, and now I apply that same ownership to software delivery. I'm strongest at turning messy, real-world requirements into clear technical workflows that people actually use."
                    ),
                ),
                (
                    "focus",
                    models.TextField(
                        default="I'm currently focused on full-stack agentic engineering and solutions/implementation roles where I can keep shipping, keep learning, and contribute to products with real customer impact."
                    ),
                ),
                (
                    "connect",
                    models.TextField(
                        default="If you're building something meaningful and need someone who can connect product, business, and engineering execution, I'd love to connect."
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "tags",
                    modelcluster.contrib.taggit.ClusterTaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="content.ContentPageTag",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RunPython(create_default_profile_page, remove_default_profile_page),
    ]
